version: '3'
services:

  web:
    image: "zsnmwy/tieba-cloud-sign"
    environment:
      DB_HOST: db:3306
      DB_USER: root
      DB_NAME: tiebacloud
      DB_PASSWD: xdj123456
      CSRF: "false"
    ports:
      - "80:8080"
    links:
      - db
    depends_on:
      - db


  db:
    image: "mysql:5.5"
    environment:
      MYSQL_DATABASE: tiebacloud
      MYSQL_ROOT_PASSWORD: xdj123456
