version: '3'
services:

  master:
    build: ./master
    command: mysqld --log-bin=/var/lib/mysql-log/binlog/mysql-bin
    ports:
      - "3306:3306"
      - "3307:3306"
      - "33000:3306"
    environment:
      MYSQL_DATABASE: root
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - ~/Docker/volumes/mysql-5.7-master:/var/lib/mysql
      - ~/Docker/volumes/mysql-5.7-master-log:/var/lib/mysql-log

  # slave:
  #   build: ./slave
  #   ports:
  #     - "33001:3306"
  #   environment:
  #     MYSQL_DATABASE: root
  #     MYSQL_ROOT_PASSWORD: 123456
  #   volumes:
  #     - ~/Docker/volumes/mysql-5.7-slave:/var/lib/mysql
