version: "3.1"
services:
  elasticsearch:
    image: elasticsearch:7.17.19
    container_name: es7
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - "discovery.type=single-node"
    volumes:
      - ./elasticsearch/config:/usr/share/elasticsearch/config
      - ./elasticsearch/data:/usr/share/elasticsearch/data # 生产环境必须打开此注释
      - ./elasticsearch/plugins:/usr/share/elasticsearch/plugins
      - ./elasticsearch/logs:/usr/share/elasticsearch/logs
    # 解决容器对本地文件无写入权限
    # user: elasticsearch
    # privileged: true

  kibana:
    image: kibana:7.17.19
    container_name: kibana7
    ports:
      - 5601:5601
    environment:
     - I18N_LOCALE=zh-CN
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
      # - ./kibana/plugins:/usr/share/kibana/plugins
    #   # - ./kibana/logs:/usr/share/kibana/logs

  logstash:
    image: logstash:7.17.19
    container_name: logstash7
    ports:
      - 5044:5044
    environment:
      - "config.reload.automatic=true" # 无需重启容器，自动重载配置
    volumes:
      - ./logstash/config:/usr/share/logstash/config
      - ./logstash/pipeline:/usr/share/logstash/pipeline
      # /usr/share/logstash/data
