version: '3'

services:
  # tag:监控数据展示及预警
  grafana:
    restart: always
    image: grafana/grafana:10.0.1
    user: root
    ports:
      - 3000:3000
    volumes:
      - './grafana/data:/var/lib/grafana'
      - './grafana/log:/var/log/grafana'
      - './conf/grafana/grafana.ini:/etc/grafana/grafana.ini'
# admin:admin docker pull prom/prometheus:v2.45.0

  # tag:监控数据存储
  prometheus:
    restart: always
    image: prom/prometheus:v2.45.0
    user: root
    ports:
      - 9090:9090
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.enable-lifecycle' # 支持配置热更新
      - '--log.level=debug'
    volumes:
      - ./conf/promethues:/etc/prometheus
      - ./promethues:/prometheus

  # tag:http监控数据采集
  blackbox-exporter:
    restart: always
    image: prom/blackbox-exporter:v0.24.0
    user: root
    ports:
      - 9115:9115
    command:
      - --config.file=/etc/blackbox/blackbox.yml
    volumes:
      - ./conf/blackbox-exporter/blackbox.yml:/etc/blackbox/blackbox.yml