version: '3'
# todo 未完成
services:
  zoo1:
    image: zookeeper:3.6.1
    # restart: always
    hostname: zoo1
    ports:
      - 2181:2181
      - 2188:2181
      - 8080:8080
    environment:
      ZOO_MY_ID: 1

  kafka1:
    image: kafka:2.8.0
    build: .
    depends_on: 
      - zoo1
    ports:
      - 9092:9092
  # kafkamanager:
  #   image: kafkamanager/kafka-manager:3.0.0.4
  #   ports:
  #     - 9000:9000
  #   environment:
  #     ZK_HOSTS: zoo1
  # docker pull kafkamanager/kafka-manager