version: '3'

services:
  mailserver:
    image: mailserver/docker-mailserver:latest
    hostname: mail
    domainname: example.com
    container_name: mailserver
    ports:
      - "25:25"
      - "143:143"
      - "465:465"
      - "587:587"
      - "993:993"
    volumes:
      - maildata:/var/mail
      - mailstate:/var/mail-state
      - maillogs:/var/log/mail
      - ./config/:/tmp/docker-mailserver/
    environment:
      - DMS_DEBUG=0
      - ENABLE_SPAMASSASSIN=1
      - ENABLE_CLAMAV=1
      - ENABLE_FAIL2BAN=1
      - ENABLE_POSTGREY=1
      - ONE_DIR=1
      - POSTMASTER_ADDRESS=postmaster@example.com
      - MAIL_USER=admin@example.com
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE
    restart: unless-stopped

  rainloop:
    image: hardware/rainloop:latest
    container_name: rainloop
    ports:
      - "8080:80"
    volumes:
      - rainloop_data:/rainloop/data
    restart: unless-stopped

volumes:
  maildata:
  mailstate:
  maillogs:
  rainloop_data:
