version: "3.1"
services:
  elasticsearch:
    image: elasticsearch:7.4.2
    container_name: es7
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - "discovery.type=single-node"
    volumes:
      - ./elasticsearch/config:/usr/share/elasticsearch/config
      - ./elasticsearch/data:/usr/share/elasticsearch/data  
    #   - ./elasticsearch/plugins:/usr/share/elasticsearch/plugins
    #   - ./elasticsearch/logs:/usr/share/elasticsearch/logs
    user: root
      
  kibana:
    image: kibana:7.4.2
    container_name: kibana7
    ports:
      - 5601:5601
    # volumes:
    #   - ./kibana/config:/usr/share/kibana/config
    #   # - ./kibana/plugins:/usr/share/kibana/plugins
    #   # - ./kibana/logs:/usr/share/kibana/logs

#   logstash:
#     image: logstash:7.4.2
#     container_name: logstash7
#     ports:
#       - 5044:5044
#     volumes:                                                                                      
#       - ./logstash/config:/usr/share/logstash/config
#       # /usr/share/logstash/data
