version: '3'
services:

  db:
    # image: "mysql:5.7.28"
    build: .
    ports:
      - "33001:3306"
    environment:
      MYSQL_DATABASE: root
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - ~/Docker/volumes/mysql-5.7-slave:/var/lib/mysql
