version: '3'
services:

  db:
    image: "mysql:5.7.28"
#    restart: always
    ports:
      - "3357:3306"
    env_file:
      - ./conf/mysql.env
    volumes:
      - ./data:/var/lib/mysql
      - ./conf/mysql.conf.d:/etc/mysql/mysql.conf.d
