version: '3'
services:

  db:
    image: "mysql:5.7.28"
#    restart: always
    ports:
      - "3309:3306"
    environment:
      MYSQL_DATABASE: root
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - ~/Docker/volumes/mysql-5.7:/var/lib/mysql
