version: "3.1"
services:
  elasticsearch:
    image: elasticsearch:2.4.1
    container_name: es2
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - "discovery.type=single-node"
    # volumes:
    #   - ~/Docker/volumes/mysql-5.7:/var/lib/mysql
  kabana:
    image: kibana:4.1.2
    container_name: kibana4
    ports:
      - 5601:5601
  