version: '3'
services:

  db:
    image: "mysql:5.6"
#    restart: always
    ports:
      - "3310:3306"
    environment:
      MYSQL_DATABASE: root
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - ~/Docker/volumes/mysql-5.6:/var/lib/mysql
