version: '3'
services:

  db:
    image: "adguard/adguardhome"
    restart: always
    ports:
      - "3000:3000"
      - "53:53/udp"
      - "67:67/udp"
      - "68:68/tcp"
      - "68:68/udp"
      - "443:443/tcp"
      - "853:853/tcp"
    volumes:
      - ~/Docker/volumes/adguardHome/conf:/opt/adguardhome/conf
      - ~/Docker/volumes/adguardHome/work:/opt/adguardhome/work
