version: '3'
services:

  adguardhome:
    image: "adguard/adguardhome:latest"
    # image: "adguard/adguardhome:v0.107.54"
    restart: always
    ports:
      - "3000:3000"
      - "53:53/udp"
      - "67:67/udp"
      - "68:68/tcp"
      - "68:68/udp"
      - "443:443/tcp"
      - "853:853/tcp"
    volumes:
      - ./conf:/opt/adguardhome/conf
      - ./work:/opt/adguardhome/work
