version: '3'
services:
  elasticsearch:
    image: elasticsearch:7.17.25
    container_name: elasticsearch-7
    restart: always
#    ports:
#      - 9200:9200
    environment:
      discovery.type: single-node  #es单机模式
      TZ: Asia/Shanghai  #时区设置
      TAKE_FILE_OWNERSHIP: true  #解决 volumes 挂载权限问题
      ES_JAVA_OPTS: -Xms256m -Xmx256m  #jvm内存分配为256MB
    ulimits:
      memlock:
        soft: -1
        hard: -1
    logging:
      options:
        max-size: "10m"
    volumes:
      - ./elasticsearch/data:/usr/share/elasticsearch/data

  kibana:
    image: kibana:7.17.25
    container_name: kibana-7
#    ports:
#      - 5601:5601
    environment:
      - I18N_LOCALE=zh-CN
    logging:
      options:
        max-size: "10m"
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
      # - ./kibana/plugins:/usr/share/kibana/plugins
    #   # - ./kibana/logs:/usr/share/kibana/logs

  oap:
    image: apache/skywalking-oap-server:10.1.0-java17
#    image: apache/skywalking-oap-server:10.1.0-java21
    container_name: skywalking-oap-10
    depends_on:
      - elasticsearch
    links:
      - elasticsearch
    restart: always
    ports:
      - 11800:11800 # 与agent交互
#      - 12800:12800 # 与ui交互
    environment:
      SW_STORAGE: elasticsearch
      SW_STORAGE_ES_CLUSTER_NODES: elasticsearch:9200
      SW_HEALTH_CHECKER: default
      SW_TELEMETRY: prometheus
    healthcheck:
      test: ["CMD", "./bin/swctl", "ch"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      options:
        max-size: "10m"

  ui:
#    image: apache/skywalking-ui:10.1.0-java21
    image: apache/skywalking-ui:10.1.0-java17
    container_name: skywalking-ui-10
    depends_on:
      - oap
    links:
      - oap
    restart: always
#    不映射宿主机端口，通过nginx添加登录验证后访问
#    ports:
#      - 13800:8080
    environment:
      SW_OAP_ADDRESS: http://oap:12800
    logging:
      options:
        max-size: "10m"

  nginx:
#    image: openresty/openresty:1.21.4.1-0-alpine
#    container_name: nginx-1_21
#    image: nginx:1.26.2-otel
#    container_name: nginx-1_26-otel
    image: nginx:1.26.2
    container_name: nginx-1_26
    depends_on:
      - ui
    links:
      - ui
    restart: always
    ports:
#      - 9999:80    # nginx默认页
      - 13800:13800 # skywalking-ui
      - 5601:5601   # kibana
    environment:
      TZ: 'Asia/Shanghai'
    logging:
      options:
        max-size: "10m"
    volumes:
      - ./nginx/logs:/var/log/nginx
      - ./nginx/etc/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/etc/conf.d:/etc/nginx/conf.d
      - ./nginx/.htpasswd:/etc/nginx/.htpasswd # 默认账号密码 skywalking:skywalking