##########################################################################
#Author : happylay 安徽理工大学
#Created Time : 2020-03-31 17:31
#Environment：centos:7.5.1804
##########################################################################
version: "3.1"
services:    
  datax-web:
    image: happylay/datax-web:v2.1.1-standalone
    container_name: datax-web
    network_mode: "host"
    restart: always     
    ports:
      - "20080:20080"
      - "20081:20081"    
      - "28848:28848"       
    volumes:
      - ./system/job:/job/json
      - ./system/applogs/admin:/data/applogs/admin
      - ./system/jobhandler:/data/applogs/executor/jobhandler
    depends_on:
      - datax-web-mysql

  datax-web-mysql:
    image: happylay/mysql:5.7-v1.0.0
    container_name: datax-web-mysql
    network_mode: "host"   
    restart: always      
    environment:       
      MYSQL_ROOT_PASSWORD: 'happylay'
      MYSQL_DATABASE: 'datax_web'
      MYSQL_USER: 'happylay'
      MYSQL_PASSWORD: 'happylay'   
    volumes:
      - ./system/mysql:/var/lib/mysql
    ports:
      - "10086:10086"
