version: '3'
services:
# docker pull minio/minio:RELEASE.2023-07-21T21-12-44Z
# https://min.io/docs/minio/container/operations/install-deploy-manage/deploy-minio-single-node-single-drive.html
# https://hub.docker.com/r/bitnami/minio/tags
  minio:
    image: "minio/minio:RELEASE.2023-07-21T21-12-44Z"
    ports:
      - "9000:9000"
      - "9090:9090"
    volumes:
      - ./data:/data
    command: server --console-address ":9090" /data
