global:
  smtp_smarthost: 'smtp.126.com:465'
  smtp_from: 'xudaojie1992@126.com'
  smtp_auth_username: 'xudaojie1992@126.com'
  smtp_auth_password: 'WTDBAMZQLAAAPCHL'
  smtp_require_tls: false
route:
  group_by: ['example']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'email'
receivers:
  - name: 'email'
    email_configs:
      # 配置接受邮箱地址
      - to : 'xudaojieg@gmail.com'
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
