version: '3'
services:

  proxy:
    image: 'apache/sharding-proxy:4.0.1'
    # restart: always
    ports:
      - "13308:3308"
    environment:
      PORT: 3308
    volumes:
      - ./conf:/opt/sharding-proxy/conf
      - ./lib:/opt/sharding-proxy/ext-lib

  # slave:
  #   build: ./slave
  #   restart: always
  #   depends_on: 
  #     - master
  #   ports:
  #     - "33001:3306"
  #   environment:
  #     MYSQL_DATABASE: root
  #     MYSQL_ROOT_PASSWORD: 123456
  #   volumes:
  #     - ~/Docker/volumes/mysql-5.7-slave:/var/lib/mysql
