version: '3'
services:
# docker run -p 27017:27017 mongo:4.0.18-xenial mongod --replSet mongoreplset
  mongodb-test:
    image: "mongo:4.0.18-xenial"
    ports:
      - "27018:27017"
    volumes:
      - mongodb:/data/db
    hostname: mongo-4018
volumes:
  mongodb:
