GRANT REPLICATION SLAVE, REPLICATION CLIENT ON *.* TO repl@'192.168.%.%' IDENTIFIED BY 'repl';
GRANT REPLICATION SLAVE, REPLICATION CLIENT ON *.* TO repl@'172.%.%.%' IDENTIFIED BY 'repl';
GRANT REPLICATION SLAVE, REPLICATION CLIENT ON *.* TO repl@'10.%.%.%' IDENTIFIED BY 'repl';
GRANT REPLICATION SLAVE, REPLICATION CLIENT ON *.* TO repl@'host.docker.internal' IDENTIFIED BY 'repl';